/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author emmat
 */
public class RechercherPatient extends javax.swing.JFrame {

    /**
     * Creates new form RechercherPatient
     */
    public RechercherPatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RechercherPatient = new javax.swing.JPanel();
        NumeroIPP = new javax.swing.JLabel();
        NumIPPTextField = new javax.swing.JTextField();
        DateNaissance = new javax.swing.JLabel();
        DateNaissanceTextField = new javax.swing.JTextField();
        NumRue = new javax.swing.JLabel();
        Rue = new javax.swing.JLabel();
        Ville = new javax.swing.JLabel();
        CodePostal = new javax.swing.JLabel();
        RueTextField = new javax.swing.JTextField();
        NumRueTextField = new javax.swing.JTextField();
        VilleTextField = new javax.swing.JTextField();
        CodePostalTextField = new javax.swing.JTextField();
        Chercher = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();
        TitrePage = new javax.swing.JLabel();
        NomTextField = new javax.swing.JTextField();
        Nom = new javax.swing.JLabel();
        Prenom = new javax.swing.JLabel();
        PrenomTextField = new javax.swing.JTextField();
        Sexe = new javax.swing.JLabel();
        SexeTextField = new javax.swing.JTextField();
        LogoCHU = new javax.swing.JLabel();
        LogoMedSolutions = new javax.swing.JLabel();
        DossierPatient = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RechercherPatient.setBackground(new java.awt.Color(255, 255, 255));

        NumeroIPP.setText("Numéro IPP");

        NumIPPTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumIPPTextFieldActionPerformed(evt);
            }
        });

        DateNaissance.setText("Date de naissance");

        DateNaissanceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateNaissanceTextFieldActionPerformed(evt);
            }
        });

        NumRue.setText("N° de rue");

        Rue.setText("Rue");

        Ville.setText("Ville");

        CodePostal.setText("Code Postal");

        RueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RueTextFieldActionPerformed(evt);
            }
        });

        VilleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VilleTextFieldActionPerformed(evt);
            }
        });

        Chercher.setText("Chercher");
        Chercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChercherActionPerformed(evt);
            }
        });

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });

        TitrePage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TitrePage.setForeground(new java.awt.Color(178, 12, 25));
        TitrePage.setText("Princeton Plainsboro - Rechercher un patient");

        Nom.setText("Nom");

        Prenom.setText("Prénom");

        Sexe.setText("Sexe");

        SexeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SexeTextFieldActionPerformed(evt);
            }
        });

        LogoCHU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.PNG"))); // NOI18N
        LogoCHU.setPreferredSize(new java.awt.Dimension(250, 414));

        LogoMedSolutions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_medsolutions.png"))); // NOI18N

        DossierPatient.setBorder(javax.swing.BorderFactory.createTitledBorder("Dossier du patient"));

        javax.swing.GroupLayout RechercherPatientLayout = new javax.swing.GroupLayout(RechercherPatient);
        RechercherPatient.setLayout(RechercherPatientLayout);
        RechercherPatientLayout.setHorizontalGroup(
            RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RechercherPatientLayout.createSequentialGroup()
                .addGroup(RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RechercherPatientLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TitrePage, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RechercherPatientLayout.createSequentialGroup()
                        .addComponent(LogoMedSolutions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DossierPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(RechercherPatientLayout.createSequentialGroup()
                                    .addComponent(DateNaissance)
                                    .addGap(24, 24, 24)
                                    .addComponent(DateNaissanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(RechercherPatientLayout.createSequentialGroup()
                                    .addComponent(NumeroIPP)
                                    .addGap(61, 61, 61)
                                    .addComponent(NumIPPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(RechercherPatientLayout.createSequentialGroup()
                                .addComponent(Nom)
                                .addGap(18, 18, 18)
                                .addComponent(NomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PrenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Sexe, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SexeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RechercherPatientLayout.createSequentialGroup()
                                .addGroup(RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(RechercherPatientLayout.createSequentialGroup()
                                        .addGroup(RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CodePostal)
                                            .addComponent(NumRue))
                                        .addGap(18, 18, 18)
                                        .addGroup(RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NumRueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CodePostalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(RechercherPatientLayout.createSequentialGroup()
                                        .addComponent(Annuler)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Chercher)))
                                .addGap(24, 24, 24)
                                .addGroup(RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RechercherPatientLayout.createSequentialGroup()
                                        .addComponent(Ville)
                                        .addGap(18, 18, 18)
                                        .addComponent(VilleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(RechercherPatientLayout.createSequentialGroup()
                                        .addComponent(Rue)
                                        .addGap(18, 18, 18)
                                        .addComponent(RueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(LogoCHU, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        RechercherPatientLayout.setVerticalGroup(
            RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RechercherPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitrePage)
                .addGroup(RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RechercherPatientLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nom)
                            .addComponent(NomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Prenom)
                            .addComponent(PrenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sexe)
                            .addComponent(SexeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumeroIPP)
                            .addComponent(NumIPPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DateNaissanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateNaissance))
                        .addGap(18, 18, 18)
                        .addGroup(RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumRue)
                            .addComponent(NumRueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rue)
                            .addComponent(RueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RechercherPatientLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CodePostal)
                                    .addComponent(CodePostalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(RechercherPatientLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Ville)
                                    .addComponent(VilleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28)
                        .addGroup(RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Chercher)
                            .addComponent(Annuler))
                        .addGap(31, 31, 31)
                        .addComponent(DossierPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RechercherPatientLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                        .addGroup(RechercherPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LogoCHU, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LogoMedSolutions))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RechercherPatient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RechercherPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumIPPTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumIPPTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumIPPTextFieldActionPerformed

    private void DateNaissanceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateNaissanceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateNaissanceTextFieldActionPerformed

    private void RueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RueTextFieldActionPerformed

    private void VilleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VilleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VilleTextFieldActionPerformed

    private void ChercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChercherActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ChercherActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // TODO add your handling code here:
        Patients p = new Patients();
        p.setVisible(true);
        this.hide();
    }//GEN-LAST:event_AnnulerActionPerformed

    private void SexeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SexeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SexeTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RechercherPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RechercherPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RechercherPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RechercherPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RechercherPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JButton Chercher;
    private javax.swing.JLabel CodePostal;
    private javax.swing.JTextField CodePostalTextField;
    private javax.swing.JLabel DateNaissance;
    private javax.swing.JTextField DateNaissanceTextField;
    private javax.swing.JScrollPane DossierPatient;
    private javax.swing.JLabel LogoCHU;
    private javax.swing.JLabel LogoMedSolutions;
    private javax.swing.JLabel Nom;
    private javax.swing.JTextField NomTextField;
    private javax.swing.JTextField NumIPPTextField;
    private javax.swing.JLabel NumRue;
    private javax.swing.JTextField NumRueTextField;
    private javax.swing.JLabel NumeroIPP;
    private javax.swing.JLabel Prenom;
    private javax.swing.JTextField PrenomTextField;
    private javax.swing.JPanel RechercherPatient;
    private javax.swing.JLabel Rue;
    private javax.swing.JTextField RueTextField;
    private javax.swing.JLabel Sexe;
    private javax.swing.JTextField SexeTextField;
    private javax.swing.JLabel TitrePage;
    private javax.swing.JLabel Ville;
    private javax.swing.JTextField VilleTextField;
    // End of variables declaration//GEN-END:variables
}
